### ISSUE TITLE
Stock Balance - SELCO Report

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#29]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 96, in run
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/frappe-bench/apps/selco/selco/selco/report/stock_balance_selco/stock_balance_selco.py", line 16, in execute
    iwb_map = get_item_warehouse_map(filters)
  File "/home/frappe/frappe-bench/apps/selco/selco/selco/report/stock_balance_selco/stock_balance_selco.py", line 88, in get_item_warehouse_map
    from_date = getdate(filters["from_date"])
KeyError: u'from_date'

**Comment by gaurav-naik** [comment]
KeyError was misleading. Error was in the report name. This has been fixed. Will push changes within the hour.

**Comment by gaurav-naik** [comment]
Fixed. Kindly verify.

**Comment by Basawa-SELCO** [comment]
working fine
