### ISSUE TITLE
Pending Rejection In From Supplier -  Report

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#32]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 90, in run
    result = [list(t) for t in frappe.db.sql(report.query, filters)]
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 166, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 163, in execute
    query = self.mogrify(query, args)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 142, in mogrify
    query = query % self._escape_args(args, conn)
KeyError: 'selco_branch'

**Comment by Basawa-SELCO** [comment]
Not fixed..please check

**Comment by Basawa-SELCO** [comment]
Any update?

**Comment by gaurav-naik** [comment]
Fix pushed 11 days ago but did not take! Will investigate and update today.

**Comment by gaurav-naik** [comment]
Report json not getting replaced. Investigating.

**Comment by gaurav-naik** [comment]
Report no longer throws an error. Can this issue be closed?
