### ISSUE TITLE
Complaint Register - Service Branchwise

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#37]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 96, in run
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 919, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 704, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/selco/selco/selco/report/complaint_register___service_branchwise/complaint_register___service_branchwise.py", line 7, in <module>
    from erpnext.hr.doctype.process_payroll.process_payroll import get_month_details
ImportError: No module named process_payroll.process_payroll

**Comment by gaurav-naik** [comment]
Fixed. Kindly verify.
