### ISSUE TITLE
Stock Entry

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#7]
Not able to save Stock Entry even after naming series has been set.

**Comment by gaurav-naik** [comment]
Am in the process of adding messages that will be shown if important Branch data is missing.

**Comment by Basawa-SELCO** [comment]
in new Stock Entry - Default Source Warehouse and Default Target Warehouse fields should not be required to select and should take automatically. In the current form, if we select the above mentoned fields, then the corresponding Address fields are coming.

In the Item Table again the  Source Warehouse and Target Warehouse fields are displayed which is not required. And the Item name column in not displayed.


Not able to save any Stock Entry
InternalError: (1054, u"Unknown column 'address' in 'field list'").

'Get Items From IBM' Button should work in Stock Entry

**Comment by gaurav-naik** [comment]
- [x] Updated Spec: 'Get Items From IBM' must filter IBMs based on "Being Dispatched To" and not by branch.
- [x] Check why default_destination_warehouse sometimes picks up the wrong address

**Comment by Basawa-SELCO** [comment]
- [x] Hide Source and Target Warehouse In Item Table

**Comment by Basawa-SELCO** [comment]
When Type Of Stock Entry == GRN, Its throwing some error.

![grn](https://user-images.githubusercontent.com/24898695/39469883-2821b8d2-4d58-11e8-93b9-e310478390e5.png)

**Comment by gaurav-naik** [comment]
> When Type Of Stock Entry == GRN, Its throwing some error.
This was because an incorrectly set warehouse in the linked Branch.

- [x] Suppliers_ref error on submit

**Comment by Basawa-SELCO** [comment]
When Type Of Stock Entry == BOM , Its throwing following error -> Deafault Source Warehouse and Default Target Warehouse can not be same.
(Ideally it should pick same warehouse when Type Of Stock Entry == BOM)

**Comment by Basawa-SELCO** [comment]
When Type Of Stock Entry == GRN and Type Of Material == Repair Stock, Its throwing following error.

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/selco/selco/selco/selco_customizations.py", line 377, in get_items_from_outward_stock_entry
    to_warehouse = frappe.db.get_value("Branch",selco_var_dc.selco_being_dispatched_to,"repair_warehouse")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 443, in get_value
    order_by, cache=cache)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 487, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 619, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 166, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'repair_warehouse' in 'field list'")

**Comment by Basawa-SELCO** [comment]
When Type Of Stock Entry == BOM (Godown) It throws valuation rate error.

**Comment by Basawa-SELCO** [comment]
When Type Of Stock Entry == BOM (Godown), Tried to add individual items manually (Instead of Get Items) it throws the error 'Source and target warehouse cannot be same'

**Comment by gaurav-naik** [comment]
Observations

1. "Valuation Rate not found" message for repack item.(e.g. CL2HLS) while saving Stock Entry
2. "Source and Target warehouse cannot be the same" for manually added items even if different Stock Warehouses are set (Investigate before_insert, validate)

**Comment by Basawa-SELCO** [comment]
Stock Entry ( Godown) Type of stock entry == Rejction Out for Repair Stock it throws following error
Unknown column 'selco_rejection_out__naming_series' in 'field list'"


Stock Entry (Godown)  Type of stock entry == Rejction Out  and Rejection Out, 'Make Material Request','Get Items From', Get Items From IBM' Buttons has to be hidden

**Comment by gaurav-naik** [comment]
Fixed:

>Stock Entry ( Godown) Type of stock entry == Rejction Out for Repair Stock it throws following error
Unknown column 'selco_rejection_out__naming_series' in 'field list'"

> When Type Of Stock Entry == BOM (Godown), Tried to add individual items manually (Instead of Get Items) it throws the error 'Source and target warehouse cannot be same'

Had to edit the the stock_entry_updates custom method to set the from and to warehouses correctly

> When Type Of Stock Entry == BOM (Godown) It throws valuation rate error.

![valuation_rate_for_kitpack](https://user-images.githubusercontent.com/17795124/39747935-56aa62ca-52cc-11e8-8c87-34722579abe7.png)

 Valuation rate can be seen for kitpack item (bottom of image, above amount). It would also appear for CL2HLS2 after opening stock reconciliation.
Alternately, the user can check Allow Zero Valuation Rate on the line item itself.

**Comment by gaurav-naik** [comment]
> Stock Entry (Godown) Type of stock entry == Rejction Out and Rejection Out, 'Make Material Request','Get Items From', Get Items From IBM' Buttons has to be hidden.

- [x] Hide specified custom buttons
