### ISSUE TITLE
Report ->Complaint Budget V2 and Complaint Budget V2 With 2 Columns

### ISSUE THREAD

**Issue by Basawa-SELCO** [Basawa-SELCO/selco_v2#98]
Not showing any data

**Comment by Basawa-SELCO** [comment]
Please add 
	
return frappe.db.sql("""SELECT A.name,A.date,A.customer_full_name,A.ics_date,A.remarks,B.service_record_number,B.service_person,B.service_record_date,B.service_amount,B.within_warranty,B.special_budget_approved_by_csd,B.budget_thirty_five,B.csd_remarks FROM `tabIssue` AS A INNER JOIN `tabService Record Details Issue` AS B ON A.name=B.parent WHERE service_branch_email_id = %s AND B.service_record_date BETWEEN %s AND %s""", (selco_branch,msd,med),as_dict=1)

**Comment by gaurav-naik** [comment]
Need to update field references

**Comment by Basawa-SELCO** [comment]
This is urgent. Please look into this.

**Comment by Basawa-SELCO** [comment]
Its throwing following error.


Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 96, in run
    res = frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 919, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 704, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/selco/selco/selco/report/complaint_budget_v2_with_2_columns/complaint_budget_v2_with_2_columns.py", line 41
    d.csd_remarks]
    ^
SyntaxError: invalid syntax

**Comment by gaurav-naik** [comment]
Fixed.
